name: Voyage Bot

on:
  schedule:
    - cron: "0 9 * * *"   # Her gün sabah 09:00'da çalışır (UTC)
  workflow_dispatch:       # Manuel çalıştırma seçeneği

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run bot
        run: |
          python bot.py

      - name: Upload debug.json
        uses: actions/upload-artifact@v3
        with:
          name: voyage-debug
          path: debug.json

