name: ETS Voyage Sorgun Bot

on:
  schedule:
    - cron: "0 7 * * *"   # Her gün sabah 07:00 UTC (~Türkiye saati 10:00)
  workflow_dispatch:        # Elle çalıştırmak için

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları indir
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Bağımlılıkları kur
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Botu çalıştır
        run: |
          python bot.py
