name: Run Strategy Bot

on:
  schedule:
    - cron: "0 3,7,11,15,19,23 * * *"   # 03:00, 07:00, 11:00, 15:00, 19:00, 23:00
  workflow_dispatch:   # Manuel başlatma

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pandas

      - name: Run strategy
        run: python strateji.py
