name: Voyage Sorgun Bot

on:
  schedule:
    - cron: "0 7 * * *"  # Her gün sabah 07:00 UTC (Türkiye saati 10:00)
  workflow_dispatch:      # Elle çalıştırabilmek için

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları çek
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Gerekli kütüphaneleri kur
        run: |
          python -m pip install --upgrade pip
          pip install requests playwright
          python -m playwright install --with-deps chromium

      - name: Botu çalıştır
        run: |
          python voyage_bot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
