name: Run Strategy Bot

on:
  schedule:
    - cron: "0 */4 * * *"   # Her 4 saatte bir çalışır (00:00, 04:00, 08:00...)
  workflow_dispatch:         # Manuel başlatma için

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pandas

      - name: Run strategy
        run: python strateji.py
