name: OKX Liquidity Bot

on:
  schedule:
    - cron: "0 */4 * * *"   # Her 4 saatte bir çalıştırır
  workflow_dispatch:        # Manuel olarak da başlatabilirsin

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Kod deposunu çek
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Gerekli paketleri yükle
        run: pip install -r requirements.txt

      - name: Botu çalıştır
        run: python okx_liquidity_bot.py
