name: Run Strategy Bot

on:
  schedule:
    - cron: "0 0,4,8,12,16,20 * * *"   # UTC → Türkiye saatiyle 03:00, 07:00, 11:00, 15:00, 19:00, 23:00
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests pandas

      - name: Run abc.py
        run: python abc.py
