name: Voyage Screenshot Bot

on:
  workflow_dispatch:   # Manuel çalıştır
  schedule:
    - cron: "0 9 * * *"   # Her gün sabah 09:00'da (UTC) çalıştır

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          pip install requests selenium webdriver-manager chromedriver-autoinstaller

      - name: Run bot
        run: python bot.py
